version: 2

models:
  - name: fct_trials_summary
    columns:
      - name: condition
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:  
                  - heart_disease
                  - diabetes
      - name: trials_count
        tests:
          - not_null
  - name: dim_condition
    columns:
      - name: condition_key
        tests:
          - unique
          - not_null
  - name: dim_status
    columns:
      - name: overall_status_key
        tests:
          - unique
          - not_null
  - name: dim_study_type
    columns:
      - name: study_type_key
        tests:
          - unique
          - not_null
